config/routes.rb
Blog::Application.routes.draw do

  resources :posts do 
    resources :comments
  end

  root 'posts#index'

get '/about' => 'pages#about'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
belongs_to :post
validates_presence_of :post_id
validates_presence_of :body
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	validates_presence_of :title
	validates_presence_of :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @post, notice: 'Comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comment }
        format.js #create.js.erb
      else
        format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:post_id, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, except: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end

    def authenticate
      authenticate_or_request_with_http_basic do |name, password|
        name == "admin" && password == "secret"
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<%= div_for comment do %>
		<p>
		<strong>Posted <%= time_ago_in_words(comment.created_at) %> ago</strong><br />
		<%= h(comment.body) %>
	</p>
	<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.number_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/create.js.erb
var new_comment = $("<%= escape_javascript(render(:partial => @comment))%>").hide();
$('#comments').prepend(new_comment);
$('#comment_<%= @comment.id %>').fadeIn('slow');
$('#new_comment')[0].reset();

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Body</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.post_id %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @comment.post_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav role="navigation" class="navbar navbar-inverse">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
       
    <a href="https://sites.google.com/a/kaplan.edu/techservice/home/"
    class="navbar-brand">Client Services</a>


        <a href="https://docs.google.com/a/kaplan.edu/document/d/1eF43AzPKSZBbvSVzyzRs9IFN6FjGkfLtm10k-iCHKAE/edit" 
        class="navbar-brand">Win 7 Master</a>

        <a href="https://docs.google.com/a/kaplan.edu/document/d/17E2W3fJNiaEgtgcTxp2QXPNXqTe46uXII9QY_tNnDBI/edit" 
        class="navbar-brand">Chrome Box Meetings Guide</a>

        <a href="https://docs.google.com/a/kaplan.edu/spreadsheets/d/12eAQKMKHgRMfTjmBgGdHpdViQhdgJywwfxXbq6C0nsI/edit#gid=123498962" 
        class="navbar-brand">CWF Win 7 Tracking</a>

        <a href="https://sites.google.com/a/kaplan.com/network-telecom/public-documen/files-for-public-use" 
        class="navbar-brand">NetOps/Telecom Site</a>

        <a href="https://docs.google.com/a/kaplan.edu/spreadsheet/ccc?key=0Ahb9Sn9F6fh9dGFWYllKRmZBdVA0eWhsY2ROblp4N3c#gid=1"
        class="navbar-brand">Duration Metrics</a>

    </div>
    <!-- Collection of nav links, forms, and other content for toggling -->
    
</nav>
<div class="center hero-unit container">

  <h1>Kaplan Desktop Ops Sound-Off Board!</h1>

<%# <%= link_to "Sign up now!", '#', class: "btn btn-large btn-primary" %>
</div>

<div class="container">
    <!-- Example row of columns -->
  <div class="row">
    <div class ="col-md-4">
    	<img src="http://www.financialplanningguide.com.au/custom/files/media/kaplan_logo_man_with_k.jpg">

        <h2>About This Site</h2>
        <p>Welcome to Kaplan's Tech Sound-Off Board!Let us know how you really feel.  </p>
        <hip><a class="btn btn-default" href="../about" role="button">View More instructions&raquo;</a></p>
  
    </div>
    <div class="col-md-8">
      <%=yield%>
    </div>
  </div>
</div>     
<footer class="footer">
  <small>
    
    Matt Salamon 2014  |   All Right Reserved   |   Only the site admin can edit, create or destroy a post

  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   'http://mattsalamon.herokuapp.com' %></li>
      <li><%= link_to "Contact", 'http://mattsalamon.herokuapp.com' %></li>
      <li><a href="http://msalamon.byethost13.com/">My Blog</a></li>
    </ul>
  </nav>
</footer>



</body>
</html>

app/views/pages/about.html.erb
<% provide(:title, '') %>

  <div class="container">
    <!-- Example row of columns -->
    <div class="row">
      <div class="col-md-2">
        <h2><%= glyph 'pencil' %></h2>
        <br>
        <p>The <%= glyph 'pencil' %> icon will show all comments for the post. Next you can add your own comment in the New Comment form field.</p>
        <p><a class="btn btn-default" href="../" role="button">Back &raquo;</a></p>
      </div>
      <div class="col-md-2">
        <h2><%= glyph 'cog'%></h2>
        <br>
        <p>The <%= glyph 'cog' %> icon is for site admin only, and allows the posts to be edited. If you are not the site administrator, don't worry about this one. </p>
        <p><a class="btn btn-default" href="../" role="button">Back &raquo;</a></p>
     </div>
      <div class="col-md-2">
        <h2><%= glyph 'trash'%></h2>
        <br>
        <p>The <%= glyph 'trash' %> icon is for site admin only, and allows the posts to be deleted. If you are not the site administrator, don't worry about this one either. </p>
        <p><a class="btn btn-default" href="../" role="button">Back &raquo;</a></p>
      </div>
    </div>

app/views/posts/_form.html.erb
<%= form_for @post, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :title, :class => 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :body, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :body, :class => 'text_field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  posts_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/index.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:body) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.id %></td>
          <td><%= post.title %></td>
          <td><%= post.body %></td>
        <td><%=l post.created_at, format: :long %></td>
        <td>
          <%= link_to post_path(post), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to edit_post_path(post), :class => 'btn btn-xs', :title => "#{ t('.edit', :default => t('helpers.links.edit')) }" do %>
            <%= glyph 'cog' %>
          <%- end -%>
          <%= link_to post_path(post), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'trash' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_post_path,
            :class => 'btn btn-primary' %>

app/views/posts/new.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/show.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:title) %></dt>
      <dd><pre class="prettyprint"><%= @post.title %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:body) %></dt>
      <dd><pre class="prettyprint"><%= @post.body %></pre></dd>
  </dl>
</div>
<h2>Comments</h2>
<div id="comments">
  <%= render :partial => @post.comments.reverse %>
</div>

<%= form_for([@post, Comment.new], remote: true) do |f| %>
  <p><%= f.label :body, "New Comment" %><br />
    <%= f.text_area :body %>
  </p>
  <p><%= f.submit "Add Comment" %></p>
<% end %>



<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              posts_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_post_path(@post), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              post_path(@post),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>